### ISSUE TITLE
Implement bootstrapping

### ISSUE THREAD

**Issue by vangroan** [vangroan/dht-python#4]
Implement the peer's ability to join an overlay network.

## Bootstrapping

The goal of the bootstrapping algorithm is to find the peer closest to the neighbourhood.

The peer performs an initial request to a known peer via it's **IP** and **port**.

The peer identifies itself by responding with its Node Id.

If it knows of another peer that's closer, it will respond with a redirect to that peer's Node Id, IP address and port.

This continues until no known peers are found.

## Messages

- [ ] `LOOKUP` - Ask another peer for a contact it knows of that is the closest to the Id given in the lookup request. Response is either a node Id or empty.

## Tasks

- [x] Run server loop. Allow `PeerServer` to handle incoming datagram messages.
- [ ] Send request messages.
- [ ] Respond with message.
- [ ] Correlate request and response.
- [ ] Server stores contact for incoming `LOOKUP` requests.
